export type SuccessTransactionData = {
  MerchantTransactionId: string;
  EPSTransactionId: string;
  Status: string;
  TotalAmount: string;
  StoreAmount: string; 
  TransactionDate: string;
  TransactionType: string;
  FinancialEntity: string;
  ErrorCode: string | null;
  ErrorMessage: string | null;
  CustomerId: string | null;
  CustomerName: string;
  CustomerEmail: string;
  CustomerAddress: string;
  CustomerAddress2: string | null;
  CustomerCity: string;
  CustomerState: string;
  CustomerPostcode: string;
  CustomerCountry: string;
  CustomerPhone: string;
  ShipmentName: string | null;
  ShipmentAddress: string | null;
  ShipmentAddress2: string | null;
  ShipmentCity: string | null;
  ShipmentState: string | null;
  ShipmentPostcode: string | null;
  ShipmentCountry: string | null;
  ValueA: string | null;
  ValueB: string | null;
  ValueC: string | null;
  ValueD: string | null;
  ShippingMethod: string | null;
  NoOfItem: number | null;
  ProductName: string;
  ProductProfile: string | null;
  ProductCategory: string | null;
  PaymentReferance: string | null;
  PaymentId: string;
}
